### ISSUE TITLE
Faraday timeouts on initialize 

### ISSUE THREAD

**Issue by brianlball** [NREL/OpenStudio-analysis-gem#73]
A user trying to submit an OSA to an OSAF instance on an internal AWS resource is experiencing timeouts when the server API tried ot initialize.  Error message is below.  The default timeout for Faraday.new() is 60 seconds, and this is when the user gets the error below.
There are timeouts in the later phases, but non on initialization. Try adding a longer timeout in the initialization phase.

`D, [2023-09-26T11:03:18.762417 #67097] DEBUG -- : Successfully required all gems for RunAnalysis`
`D, [2023-09-26T11:03:18.762980 #67097] DEBUG -- : RunAnalysis command: ["/Users/XXXX/folder/osa.json", "http://intern.us-west-2.elb.amazonaws.com"] {:debug=>true, :dencity=>false, :zip_file=>nil, :analysis_type=>"lhs"}`
`Traceback (most recent call last):`
`    23: from /Applications/ParametricAnalysisTool-3.6.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta:1112:in '<main>'`
`    22: from /Applications/ParametricAnalysisTool-3.6.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta:231:in 'execute'`
`    21: from /Applications/ParametricAnalysisTool-3.6.0/ParametricAnalysisTool.app/Contents/Resources/OpenStudio-server/bin/openstudio_meta:878:in 'execute'`
`    20: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/bundler/gems/OpenStudio-analysis-gem-eb523e13dd82/lib/openstudio/analysis/server_api.rb:762:in 'run'`
`    19: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/bundler/gems/OpenStudio-analysis-gem-eb523e13dd82/lib/openstudio/analysis/server_api.rb:101:in 'new_project'`
`    18: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/connection.rb:279:in 'post'`
`    17: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/connection.rb:492:in 'run_request'`
`    16: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/rack_builder.rb:153:in 'build_response'`
`    15: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/request/url_encoded.rb:25:in 'call'`
`    14: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/response/logger.rb:25:in 'call'`
`    13: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/response.rb:11:in 'call'`
`    12: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:68:in 'call'`
`    11: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter.rb:60:in 'connection'`
`    10: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:70:in 'block in call'`
`     9: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:128:in 'perform_request'`
`     8: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:137:in 'request_with_wrapped_block'`
`     7: from /Users/XXXX/folder/.bundle/install/ruby/2.7.0/gems/faraday-1.0.1/lib/faraday/adapter/net_http.rb:152:in 'request_via_request_method'`
`     6: from /Users/XXXX/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:932:in 'start'`
`     5: from /Users/XXXX/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:943:in 'do_start'`
`     4: from /Users/XXXX/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:958:in 'connect'`
`     3: from /Users/XXXX/.rbenv/versions/2.7.2/lib/ruby/2.7.0/timeout.rb:105:in 'timeout'`
`     2: from /Users/XXXX/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:960:in 'block in connect'`
`     1: from /Users/XXXX/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:960:in 'open'`
`/Users/XXXX/.rbenv/versions/2.7.2/lib/ruby/2.7.0/net/http.rb:960:in 'initialize': execution expired (Net::OpenTimeout)`

**Comment by brianlball** [comment]
we also saw timeouts on 'new_analysis' during the POST to the NREL internal cloud.
try bumping all the timeouts and write_timeouts
